### ISSUE TITLE
Suggestion: Craft green dye by combining lime green and black dyes

### ISSUE THREAD

**Issue by HalfOfAKebab** [Joshimuz/VanillaWithFlake#13]
Fuck smelting cactus when I have lime green and black dyes already

**Comment by Joshimuz** [comment]
"Lime" is basically just light green, but with all the other "light" variants of dye you can't un-light one using this method. So for example you can't turn light blue dye to blue using black. If anything Light Blue dye is an outlier as the only non-greyscale dye to feature "lightening" with white dye, and I think changing whole all the dye colours work fundamentally is a bit out of scope.
