### ISSUE TITLE
Suggestion: Punching Glow Squid gives Glowing or Night Vision effect

### ISSUE THREAD

**Issue by rybak** [Joshimuz/VanillaWithFlake#18]
Similarly to how punching regular Squid gives Blindness in Vanilla with Flake, punching Glow Squid could give some effect too.

https://minecraft.fandom.com/wiki/Glow_Squid

**Comment by rybak** [comment]
Or maybe it should also give Blindness, just like the regular Squid.

**Comment by Joshimuz** [comment]
I liked Night Vision, would be useful in caves and a fun effect so I added that
23aacd08c438f9a7c1c296403610ba4df9af3613
