### ISSUE TITLE
Suggestion: Craft a sticky piston with honey

### ISSUE THREAD

**Issue by anny-moose** [Joshimuz/VanillaWithFlake#20]
Allow crafting a sticky piston with both slime balls and honey bottles

**Comment by Joshimuz** [comment]
I've thought about this before but
1. Isn't it weird that sticky pistons are green though?
2. In redstone (and piston moving stuff specifically) honey and slime blocks attach differently, I don't want to cause confusion by having people think there's a difference between honey and slime-d sticky pistons.

**Comment by anny-moose** [comment]
As far as i know, the main difference between slime and honey, is that you can't use honey to transmit a signal, because honey is a transparent block(and it doesn't make stuff bounce)
